//%attributes = {"invisible":true}

C_LONGINT:C283(Cmd1)
C_LONGINT:C283(Cmd2)
C_LONGINT:C283(Cmd3)
C_TEXT:C284(fileBuffer_buffer)
C_TEXT:C284(fileBuffer_charSet)
C_TEXT:C284(fileBuffer_csv_separator)
C_LONGINT:C283(fileBuffer_curPos)
C_TIME:C306(fileBuffer_DocRef)
C_LONGINT:C283(fileBuffer_DocSize)
C_LONGINT:C283(fileBuffer_MaxSize)
C_TEXT:C284(File_GenerateUniqueName)
C_TEXT:C284(gError)
C_TEXT:C284(UnitTest_CurrentTestCase)
C_BOOLEAN:C305(UnitTest_hasInited)
C_TEXT:C284(UnitTest_Log)
C_LONGINT:C283(UnitTest_RunButton)
C_LONGINT:C283(UnitTest_SaveButton)
C_LONGINT:C283(UnitTest_StartTime)
C_REAL:C285(UnitTest_TotalDuration)
C_LONGINT:C283(UnitTest_TotalFailed)
C_LONGINT:C283(UnitTest_TotalPassed)
C_LONGINT:C283(UnitTest_TotalTests)